"use strict";
let car = 'Toyota';
let age = 21;
let temperature = 25;
let isRaining = true;
let fruit = 'Mango';
console.log("Is car == 'subaru'?");
console.log(car == 'subaru');
console.log("Is age >= 18? ");
console.log(age >= 18);
console.log("Is temperature < 20?");
console.log(temperature < 20);
console.log("Is isRaining == true? ");
console.log(isRaining);
console.log("Is fruit != 'banana'?");
console.log(fruit != 'banana');
console.log("Is age < 10? ");
console.log(age < 10);
console.log("Is temperature > 30?");
console.log(temperature < 30);
console.log("Is isRaining == false?");
console.log(!isRaining);
console.log("Is fruit == 'Mango'? ");
console.log(fruit == 'Mango');
console.log("Is age === 18? ");
console.log(age === 18);
